### ISSUE TITLE
Remove `eslint-disable no-restricted-imports` for styled-components

### ISSUE THREAD

**Issue by nbhargava** [Recidiviz/case-triage#78]
**What needs to be done? Why does it need to be done?**
We do not seem to be able to find `createGlobalStyle` "styled-components/macro". It's present in the `cjs` version but not the `esm` which we seem to be importing from. We thus have to override the restrictions on imports until the upstream issue is fixed.

There also seem to be a lot of imports in our package that cause the build to fail when importing our macro, we should look into them.

**Additional context**
https://github.com/styled-components/styled-components/issues/3458 was filed and once fixed/pushed, this import issue can likely also be fixed.

**Comment by macfarlandian** [comment]
turns out rollup needs a babel plugin to be able to process the "Babel macro" flavor of styled components ... I am looking into whether it's better to include that or just disable the lint rule
