### ISSUE TITLE
[Triage View] Triage List - Types and Filters

### ISSUE THREAD

**Issue by jessex** [Recidiviz/case-triage#8]
**Is your feature request related to a problem? Please describe.**
The center of the triage view is the triage list, which shows the cases that are currently relevant to help surface information intended to provide support and avoid letting negative outcomes percolate.

**Describe the solution you'd like**
(This is where the current mock-up says ‘Triage: Early Discharges’ and ‘Sort by: Needs’)

These are dropdowns that filter and prioritize the list of rows shown beneath them. 

**Triage Type**
The triage type dropdown includes the following options: ‘Early Discharge’, ‘Supervision Downgrade’, ‘Needs: F2F Contact’, and ‘Needs: Assessment’. It will filter the rows shown in the triage list to only show those rows that match those triage requirements, i.e. clients that may be eligible for [early discharge](https://docs.google.com/document/d/1WfCbUwOHekurVNDPcQWdjAZ_5yUggiArZ2hIU_72aPM/edit#heading=h.j5fdp7mpycgs), clients that may be eligible for a [supervision downgrade](https://docs.google.com/document/d/1WfCbUwOHekurVNDPcQWdjAZ_5yUggiArZ2hIU_72aPM/edit#heading=h.tmn9d3su6xit), clients that may need a [face-to-face contact](https://docs.google.com/document/d/1WfCbUwOHekurVNDPcQWdjAZ_5yUggiArZ2hIU_72aPM/edit#heading=h.l1j16d9pihm0), and clients that may need an [assessment](https://docs.google.com/document/d/1WfCbUwOHekurVNDPcQWdjAZ_5yUggiArZ2hIU_72aPM/edit#heading=h.1oco4eyaccsb). 

Whether this data will be supplied as, for example, simple boolean flags on each client row object that leads to a row in the triage list or if the app will derive whether to filter a row with logic based on other fields in the client object is still to be determined. If that call has not been made by the time this ticket is reached, assume that each client object will have a simple boolean flag and that the filters just need to check those flags.

**Sort By**
The sort dropdown includes the following options: ‘Urgency’ (how far past-due the action is), ‘Supervision type’ (Parole vs. Probation), and ‘Supervision level’. For Supervision Type, we will simply sort by placing all Parole rows first followed by all Probation rows. For Supervision Level, we will sort in ascending order of supervision levels. For both of these, these are fields on each client row object.

For Urgency, we will need to check for a particular field on the client row object that matches the selected triage type (from the previous dropdown). Each client row object will have a timestamp for each triage type that indicates the next time that particular action should have been taken (e.g. when someone became eligible for early discharge or a face-to-face contact became due). These dates may have been in the past (they are already overdue). Regardless of whether they are in the past or the future, when Urgency is selected, we will pick the timestamps corresponding to the selected Triage Type and sort by those timestamps in ascending order.

**Describe alternatives you've considered**
N/A

**Additional context**
The dropdowns are described at a high-level in the [PRD, here](https://docs.google.com/document/d/1WfCbUwOHekurVNDPcQWdjAZ_5yUggiArZ2hIU_72aPM/edit#heading=h.m9m0xmjg0jx5). More specific information is included in additional links to the PRD inline above.

**Comment by annaliseirby** [comment]
Closing in favor of https://github.com/Recidiviz/case-triage/issues/31
